config setup 
    charondebug="ike 2, cfg 2" 

conn %default 
    keyexchange=ikev2 
    ike=aes256-sha2_256-modp2048! 
    esp=aes256-sha2_256! 
    leftfirewall=yes 
    leftsubnet=10.0.1.0/24 
    rightsubnet=10.0.2.0/24 

conn right-to-left 
    right=172.17.0.3
    rightid="C=IN, O=IPsec Lab, CN=right.site.lab" 
    rightcert=right-cert.pem 
    rightsendcert=always 
    left=172.17.0.2
    leftid="C=IN, O=IPsec Lab, CN=left.site.lab" 
    auto=start 

