config setup
    # Uncomment to enable logging to syslog
    # charondebug="ike 2, knl 2, cfg 2"
    uniqueids=no

conn my-site-to-site
    # Left side (our Docker container's perspective)
    left=172.17.0.2
    leftsubnet=10.0.1.0/24

    # Right side (remote VPN peer's perspective)
    right=172.17.0.3
    rightsubnet=10.0.2.0/24

    # Authentication methods
    authby=secret
    auto=start
    keyexchange=ikev2
    type=tunnel
    compress=no
    ikelifetime=60m
    keylife=20m
    
    # Use vti for route-based VPN (needs kernel support)
    # vti=vti0
    install_routes=yes # strongswan manages the routing tables
    ike=aes256-sha256-modp2048!
    esp=aes256-sha256!

